const mongoose = require("mongoose");

const eventClassesSchema = mongoose.Schema({
    name: String,
    isValid: {type:Boolean, default: true},

  // BOYS
  boys6Class: String,
  boys6Fee: Number,
  boys7Class: String,
  boys7Fee: Number,
  boys8Class: String,
  boys8Fee: Number,
  boys9Class: String,
  boys9Fee: Number,
  boys10Class: String,
  boys10Fee: Number,
  boys11Class: String,
  boys11Fee: Number,
  boys12Class: String,
  boys12Fee: Number,
  boys13Class: String,
  boys13Fee: Number,
  boys14Class: String,
  boys14Fee: Number,
  boys15Class: String,
  boys15Fee: Number,
  boys16Class: String,
  boys16Fee: Number,
  men17Class: String,
  men17Fee: Number,
  men25Class: String,
  men25Fee: Number,
  men30Class: String,
  men30Fee: Number,
  men35Class: String,
  men35Fee: Number,
  menJuniorClass: String,
  menJuniorFee: Number,
  menUnder23Class: String,
  menUnder23Fee: Number,
  menEliteClass: String,
  menEliteFee: Number,
  // GIRLS
  girls7Class: String,
  girls7Fee: Number,
  girls8Class: String,
  girls8Fee: Number,
  girls9Class: String,
  girls9Fee: Number,
  girls10Class: String,
  girls10Fee: Number,
  girls11Class: String,
  girls11Fee: Number,
  girls12Class: String,
  girls12Fee: Number,
  girls13Class: String,
  girls13Fee: Number,
  girls14Class: String,
  girls14Fee: Number,
  girls15Class: String,
  girls15Fee: Number,
  girls16Class: String,
  girls16Fee: Number,
  women17Class: String,
  women17Fee: Number,
  women25Class: String,
  women25Fee: Number,
  womenJuniorClass: String,
  womenJuniorFee: Number,
  womenUnder23Class: String,
  womenUnder23Fee: Number,
  womenEliteClass: String,
  womenEliteFee: Number,
  // CRUISER
  boys12CrClass: String,
  boys12CrFree: Number,
  boys13CrClass: String,
  boys13CrFee: Number,
  boys15CrClass: String,
  boys15CrFee: Number,
  men17CrClass: String,
  men25CrClass: String,
  men25CrFee: Number,
  men30CrClass: String,
  men30CrFee: Number,
  men35CrClass: String,
  men35CrFee: Number,
  men40CrClass: String,
  men40CrFee: Number,
  men50CrClass: String,
  men50CrFee: Number,

  girls12CrClass: String,
  girls12CrFee: Number,
  girls16CrClass: String,
  girls16CrFee: Number,
  women17CrClass: String,
  women17CrFee: Number,
  women30CrClass: String,
  women30CrFee: Number,
  women40CrClass: String,
  women40CrFee: Number,
});

const EventClasses = mongoose.model("EventClasses", eventClassesSchema);

module.exports = EventClasses;
